--- #YAML:1.0
name:               CGI-Application-Plugin-PageLookup
version:            1.2
abstract:           Database driven model framework for CGI::Applicaition
author:
    - Nicholas Bamber <nicholas@periapt.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Application:     4.31
    CGI::Application::Plugin::DBH:  0
    CGI::Application::Plugin::Forward:  0
    HTML::Template::Pluggable:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
