--- #YAML:1.0
name:               CGI-Application-Plugin-PageLookup
version:            1.6_2
abstract:           Database driven model framework for CGI::Application
author:
    - Nicholas Bamber <nicholas@periapt.co.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    CGI:                  0
    CGI::Application:     4.31
    CGI::Application::Plugin::DBH:  0
    CGI::Application::Plugin::Forward:  0
    DBI:                  0
    HTML::Template:       0
    HTML::Template::Pluggable:  0
    Test::Database:       1.07
    Test::Differences:    0
    Test::More:           0
    UNIVERSAL::require:   0
    XML::LibXML:          0
resources:
    repository:  http://github.com/periapt/cgi-application-plugin-pagelookup
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
