---
name: CGI-Application-Plugin-PageLookup
version: 1.8
author:
  - 'Nicholas Bamber <nicholas@periapt.co.uk>'
abstract: Database driven model framework for CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/periapt/cgi-application-plugin-pagelookup/tree
build_requires:
  Test::Database: 1.07
  Test::Differences: 0
  Test::More: 0
  XML::LibXML: 0
requires:
  CGI: 0
  CGI::Application: 4.31
  CGI::Application::Plugin::DBH: 0
  CGI::Application::Plugin::Forward: 0
  Carp: 0
  DBI: 0
  HTML::Template: 0
  HTML::Template::Pluggable: 0
  UNIVERSAL::require: 0
configure_requires:
  Module::Build: 0.35
provides:
  CGI::Application::Plugin::PageLookup:
    file: lib/CGI/Application/Plugin/PageLookup.pm
    version: 1.8
  CGI::Application::Plugin::PageLookup::Href:
    file: lib/CGI/Application/Plugin/PageLookup/Href.pm
    version: 1.8
  CGI::Application::Plugin::PageLookup::Loop:
    file: lib/CGI/Application/Plugin/PageLookup/Loop.pm
    version: 1.8
  CGI::Application::Plugin::PageLookup::Menu:
    file: lib/CGI/Application/Plugin/PageLookup/Menu.pm
    version: 1.8
  CGI::Application::Plugin::PageLookup::Value:
    file: lib/CGI/Application/Plugin/PageLookup/Value.pm
    version: 1.8
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - cgiapp
  - Titanium
  - framework
  - sitemap
